backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string", default: "/blog/{{slug}}", hidden: true}
      - {label: "Title", name: "title", widget: "string", required: true }
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Anh Vo", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Body", name: "body", widget: "markdown"}